---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${APP_NAME}
  template: build
metadata:
  name: build
parameters:
- displayName: Pipeline Build Number
  name: PIPELINE_BUILD_NUMBER
  value: "0"
- displayName: Pipeline Build Source
  name: PIPELINE_BUILD_SOURCE
  value: sandbox
- displayName: Pipeline Build Branch
  name: PIPELINE_BUILD_BRANCH
  value: sandbox
- displayName: Pipeline Build Commit
  name: PIPELINE_BUILD_COMMIT
  value: sandbox
- displayName: Service Name
  name: APP_NAME
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    annotations:
      pipeline-build-number: ${PIPELINE_BUILD_NUMBER}
      pipeline-build-source: ${PIPELINE_BUILD_SOURCE}
      pipeline-build-branch: ${PIPELINE_BUILD_BRANCH}
      pipeline-build-commit: ${PIPELINE_BUILD_COMMIT}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:${PIPELINE_BUILD_NUMBER}
    source:
      type: Binary
      contextDir: content
    strategy:
      sourceStrategy:
        env:
        - name: PIPELINE_BUILD_NUMBER
          value: ${PIPELINE_BUILD_NUMBER}
        - name: PIPELINE_BUILD_SOURCE
          value: ${PIPELINE_BUILD_SOURCE}
        - name: PIPELINE_BUILD_BRANCH
          value: ${PIPELINE_BUILD_BRANCH}
        - name: PIPELINE_BULID_COMMIT
          value: ${PIPELINE_BUILD_COMMIT}
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: openshift
      type: Source
    triggers: []
