---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${APP_NAME}
  template: deploy
metadata:
  name: deploy
parameters:
- displayName: Build Namespace
  name: BUILD_NAMESPACE
  required: true
- displayName: CPU LIMIT
  name: CPU_LIMIT
  value: 500m
- displayName: CPU Request
  name: CPU_REQUEST
  value: 100m
- displayName: Memory LIMIT
  name: MEMORY_LIMIT
  value: 256Mi
- displayName: Memory Request
  name: MEMORY_REQUEST
  value: 128Mi
- displayName: Pipeline Build Number
  name: PIPELINE_BUILD_NUMBER
  value: "0"
- displayName: Pipeline Build Source
  name: PIPELINE_BUILD_SOURCE
  value: sandbox
- displayName: Pipeline Build Branch
  name: PIPELINE_BUILD_BRANCH
  value: sandbox
- displayName: Pipeline Build Commit
  name: PIPELINE_BUILD_COMMIT
  value: sandbox
- displayName: Route Hostname
  name: ROUTE_HOST
  required: false
- displayName: Application Name
  name: APP_NAME
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    annotations:
      pipeline-build-number: ${PIPELINE_BUILD_NUMBER}
      pipeline-build-source: ${PIPELINE_BUILD_SOURCE}
      pipeline-build-branch: ${PIPELINE_BUILD_BRANCH}
      pipeline-build-commit: ${PIPELINE_BUILD_COMMIT}
  spec:
    replicas: 2
    selector:
      app: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
        name: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: docker-registry.default.svc:5000/${BUILD_NAMESPACE}/${APP_NAME}:${PIPELINE_BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${APP_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
  spec:
    host: ${ROUTE_HOST}
    to:
      kind: Service
      name: ${APP_NAME}
