---
apiVersion: v1
kind: Template
labels:
  app: ${APP_NAME}
  template: test
metadata:
  name: test
parameters:
- displayName: Service Name
  name: APP_NAME
  required: true
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: ${APP_NAME}-test
  spec:
    containers:
    - name: test
      image: docker-registry.default.svc:5000/openshift/python:latest
      command: ['/bin/sh', '-c', 'for TEST in /tests/*.sh; do source $TEST; done']
      env:
      - name: APP_SERVICE_NAME
        value: ${APP_NAME}
      volumeMounts:
      - mountPath: /tests
        name: tests
    restartPolicy: Never
    volumes:
    - name: tests
      configMap:
        defaultMode: 0644
        name: ${APP_NAME}-test-scripts
